# Generated by Django 4.0.3 on 2023-06-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.IntegerField(default=None, max_length=5, unique=True),
        ),
    ]
