# Generated by Django 4.0.3 on 2023-06-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.TextField(default=None, max_length=20),
        ),
    ]
