# Generated by Django 4.0.3 on 2023-06-06 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sale_id',
            field=models.PositiveIntegerField(default=None, unique=True),
        ),
    ]
